# Generated by Django 3.1.6 on 2021-02-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Username',
            new_name='username',
        ),
    ]
