# Generated by Django 3.1.6 on 2021-02-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0002_auto_20210221_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
